[package]
name = "tv"
version = "0.1.0"
authors = ["Lukáš Hozda <luk.hozda@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1"
chrono = "0.4.6"
serde = "1.0.90"
serde_derive = "1.0.90"
promptly = "0.1.5"
yansi = "0.5.0"
